apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-orders-api
  name: customer-orders-api
spec:
  ports:
      - port: 80
        targetPort: 8000
  type: LoadBalancer
  selector:
    app: customer-orders-api

