apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: customer-orders-api-secrets
                key: db_password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: customer-orders-api-secrets
                key: db_user
          - name: POSTGRES_NAME
            valueFrom:
              secretKeyRef:
                name: customer-orders-api-secrets
                key: db_name
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: init-scripts
          configMap:
            name: postgres-init-scripts

